### ISSUE TITLE
Programming Support

### ISSUE THREAD

**Issue by mhughes2** [callwyat/mplab-extension#27]
Since it's possible to debug, which requires the micro to be programmed, how is it not possible to program the micro directly with this extension?

**Comment by callwyat** [comment]
Excellent question! It is possible, but the solution is surprisingly more complicated than when programming to debug.

Microchip provides 2 ways to program a chip. The “production” way is using MPLABX IPE. The issue with this solution is that it is an option item that can be installed with the IDE, and therefore isn’t a 100% reliable way to program the chip. The other way is to use the Microchip Debugger (MDB) which is what the debugger uses, but the programmer will hold the target device in reset, which I didn’t think was super useful. It turns out there is a ‘-p’ flag that can be passed the the MBD to release the reset, but it’s bug out on macOS, which I do my development on, and doesn’t release the reset.

With all of that being said, it has been a while since I tried, so I will take a swing at it again.

A question for you, do you think the better user interface is via the command pallet or a task?

Thanks!

**Comment by callwyat** [comment]
v0.2.0 has released with the ability to program a device with either the Microchip Debugger (which doesn't release the reset when ran on macOS) and the Microchip Integrated Programing Environment (IPE). Review the ReadMe to see how it works :).
