### ISSUE TITLE
如何自定义编译器路径 (How to customize the compiler path)

### ISSUE THREAD

**Issue by Shan-hub** [callwyat/mplab-extension#5]
进行编译的时候提示找不到编译器路径，我看到默认的在c盘，但是我的软件路径是在d盘，在扩展设置里也没找到插件的设置参数，请问这个插件支持编译器路径进行自定义设置吗？

**Comment by callwyat** [comment]
Thanks for submitting this issue. The extension currently only supports for finding MPLAB compilers that are installed in the default location, which for Windows, is in the C drive.

I am not sure how I could find it in alternative locations, unless I could find it using the systems PATH variable. Do you know if the compiler can be found using the systems PATH variable?

**Comment by edyson1904** [comment]
hi @callwyat  
I'm also trying to build a project using the extension and I have an error that it's not finding xc.h. I think the issue is that, at some point. Microchip changed its system and headers are now in family packs. For example, for a dsPIC33CK, the xc.h is in C:\Program Files\Microchip\MPLABX\v6.05\packs\Microchip\dsPIC33CK-MC_DFP\1.5.126\xc16\support\generic\h 
The default compiler location C:\Program Files\Microchip\xc16\v2.00\bin.

How is the extension invoking compilers?
Thanks!

**Comment by zhang00956** [comment]
I also find the same problem,because MPLAB install at D drive.but I have add "MPLABX\gnuBins\gnuWin32\bin" in the systems PATH。it still show an error：正在执行任务: ""c:\Program Files (x86)\Microchip\MPLABX\gnuBins\gnuWin32\bin\make.exe" CONF="default"" 系统找不到指定的路径。

**Comment by zhang00956** [comment]
I find a new  solution。@Shan-hub
1、在工程文件夹中，创建build.bat文件。
2、bat文件内写入以下内容：

cd ./pic32mz_lunch.X    @REM进入到Makefile文件夹内执行

if "%1" == "build" (
    D:/MPLAB/gnuBins/GnuWin32/bin/make.exe -j -f ./Makefile CONF=default   @REM =default是因为工程默认名字是default
) else if "%1" == "clean" (   
    D:/MPLAB/gnuBins/GnuWin32/bin/make.exe -f ./Makefile clean
) else (
    echo !!!unknown build type!!
)
exit

3、最后在vscode的终端中执行 build.bat build 可以编译 build.bat clean 可以清理工程


[build.bat.txt](https://github.com/callwyat/mplab-extension/files/11048043/build.bat.txt)

**Comment by callwyat** [comment]
I put some thought towards this issue and decided the best answer was to create the MPLABXFolderLocation setting. This setting will allow you to manually enter the path where you installed MPLABX. To access it you will need to update to v0.1.6 of the extension, open up VSCodes Settings, and search for MPLABX, where you can then enter your path.
